// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.TimeTable", b =>
                {
                    b.Property<int>("TimeTableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppUserUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUserLostTheWord")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastWordLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextWordLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeTableID");

                    b.HasIndex("AppUserUserId");

                    b.ToTable("TimeTable");
                });

            modelBuilder.Entity("API.Entities.TimeTable", b =>
                {
                    b.HasOne("API.Entities.AppUser", "AppUser")
                        .WithMany("TimeTable")
                        .HasForeignKey("AppUserUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Navigation("TimeTable");
                });
#pragma warning restore 612, 618
        }
    }
}
